INSERT INTO public."Categories" ("Name","CreatedAt","UpdatedAt","TenantId") VALUES ('ARMÁRIO SUPERIOR (INDENTIFICAR BOLSAS)',NOW(),NOW(),2);
INSERT INTO public."Categories" ("Name","CreatedAt","UpdatedAt","TenantId") VALUES ('1)  KIT LACRADOS  ',NOW(),NOW(),2);
INSERT INTO public."Categories" ("Name","CreatedAt","UpdatedAt","TenantId") VALUES ('2) ENXOVAL',NOW(),NOW(),2);
INSERT INTO public."Categories" ("Name","CreatedAt","UpdatedAt","TenantId") VALUES ('3) PAINEL (PROTEGER COM PLÁSTICO)',NOW(),NOW(),2);
INSERT INTO public."Categories" ("Name","CreatedAt","UpdatedAt","TenantId") VALUES ('PAINEL (KIT RESPIRATÓRIO)',NOW(),NOW(),2);
INSERT INTO public."Categories" ("Name","CreatedAt","UpdatedAt","TenantId") VALUES ('PRATELEIRAS (IDENTIFICAR POTES)',NOW(),NOW(),2);
INSERT INTO public."Categories" ("Name","CreatedAt","UpdatedAt","TenantId") VALUES ('4) POTE PRINCIPAL (ABERTO)',NOW(),NOW(),2);
INSERT INTO public."Categories" ("Name","CreatedAt","UpdatedAt","TenantId") VALUES ('5) POTE EPI´S',NOW(),NOW(),2);
INSERT INTO public."Categories" ("Name","CreatedAt","UpdatedAt","TenantId") VALUES ('6) MATERIAIS DIVERSOS',NOW(),NOW(),2);
INSERT INTO public."Categories" ("Name","CreatedAt","UpdatedAt","TenantId") VALUES ('7) POTE GRANDE: MATERIAIS ESTERILIZADOS',NOW(),NOW(),2);
INSERT INTO public."Categories" ("Name","CreatedAt","UpdatedAt","TenantId") VALUES ('8)  SOROS DIVERSOS',NOW(),NOW(),2);
INSERT INTO public."Categories" ("Name","CreatedAt","UpdatedAt","TenantId") VALUES ('9) ARMÁRIO INFERIOR',NOW(),NOW(),2);
INSERT INTO public."Categories" ("Name","CreatedAt","UpdatedAt","TenantId") VALUES ('10) EQUIPAMENTOS USA',NOW(),NOW(),2);
INSERT INTO public."Categories" ("Name","CreatedAt","UpdatedAt","TenantId") VALUES ('11) MATERIAL DE TRAUMA',NOW(),NOW(),2);
INSERT INTO public."Categories" ("Name","CreatedAt","UpdatedAt","TenantId") VALUES ('BOLSA BOMBA DE INFUSÃO/VENTILADOR',NOW(),NOW(),2);
INSERT INTO public."Categories" ("Name","CreatedAt","UpdatedAt","TenantId") VALUES ('13) BOLSO TRASEIRO',NOW(),NOW(),2);
INSERT INTO public."Categories" ("Name","CreatedAt","UpdatedAt","TenantId") VALUES ('14) BOLSO INTERNO',NOW(),NOW(),2);
INSERT INTO public."Categories" ("Name","CreatedAt","UpdatedAt","TenantId") VALUES ('EQUIPAMENTOS USB',NOW(),NOW(),2);
INSERT INTO public."Categories" ("Name","CreatedAt","UpdatedAt","TenantId") VALUES ('12) BOLSA APH',NOW(),NOW(),2);
INSERT INTO public."Categories" ("Name","CreatedAt","UpdatedAt","TenantId") VALUES ('BOLSO FRONTAL',NOW(),NOW(),2);
INSERT INTO public."Categories" ("Name","CreatedAt","UpdatedAt","TenantId") VALUES ('15) BOLSOS LATERAIS',NOW(),NOW(),2);
INSERT INTO public."Categories" ("Name","CreatedAt","UpdatedAt","TenantId") VALUES ('16) MALETA DE MEDICAMENTOS',NOW(),NOW(),2);
INSERT INTO public."Categories" ("Name","CreatedAt","UpdatedAt","TenantId") VALUES ('1) PARTE SUPERIOR ',NOW(),NOW(),2);
INSERT INTO public."Categories" ("Name","CreatedAt","UpdatedAt","TenantId") VALUES ('MALETA/MEDICAÇÃO PARTE SUPERIOR',NOW(),NOW(),2);
INSERT INTO public."Categories" ("Name","CreatedAt","UpdatedAt","TenantId") VALUES ('PSICOTRÓPICOS - LACRADO',NOW(),NOW(),2);
INSERT INTO public."Categories" ("Name","CreatedAt","UpdatedAt","TenantId") VALUES ('2) PARTE INFERIOR - AMPOLAS',NOW(),NOW(),2);
INSERT INTO public."Categories" ("Name","CreatedAt","UpdatedAt","TenantId") VALUES ('BOLSA APH',NOW(),NOW(),2);
INSERT INTO public."Categories" ("Name","CreatedAt","UpdatedAt","TenantId") VALUES ('1) Bolso Frontal - Acesso Venoso',NOW(),NOW(),2);
INSERT INTO public."Categories" ("Name","CreatedAt","UpdatedAt","TenantId") VALUES ('2) Bolso Lateral - Laringo',NOW(),NOW(),2);
INSERT INTO public."Categories" ("Name","CreatedAt","UpdatedAt","TenantId") VALUES ('BOLSA SSVV',NOW(),NOW(),2);
INSERT INTO public."Categories" ("Name","CreatedAt","UpdatedAt","TenantId") VALUES ('3) Bolso Lateral - Respiratório',NOW(),NOW(),2);
INSERT INTO public."Categories" ("Name","CreatedAt","UpdatedAt","TenantId") VALUES ('EQUIPAMENTOS',NOW(),NOW(),2);
INSERT INTO public."Categories" ("Name","CreatedAt","UpdatedAt","TenantId") VALUES ('4) Bolso traseiro -  Kit Entubação',NOW(),NOW(),2);
INSERT INTO public."Categories" ("Name","CreatedAt","UpdatedAt","TenantId") VALUES ('5) Bolso Interno - Diversos',NOW(),NOW(),2);
INSERT INTO public."Categories" ("Name","CreatedAt","UpdatedAt","TenantId") VALUES ('MALETA MEDICAMENTOS',NOW(),NOW(),2);
INSERT INTO public."Categories" ("Name","CreatedAt","UpdatedAt","TenantId") VALUES ('1) Parte Superior',NOW(),NOW(),2);
INSERT INTO public."Categories" ("Name","CreatedAt","UpdatedAt","TenantId") VALUES ('Medicações controladas lacrada? Sim ou Não?',NOW(),NOW(),2);

INSERT INTO public."Categories" ("Name","CreatedAt","UpdatedAt","TenantId") VALUES ('Maletas',NOW(),NOW(),2);
