INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('KIT CATETERISO VESICAL', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('KIT ATADURAS', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('KIT SUTURA', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('KIT PROCEDIMENTOS INVASIVOS', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('KIT PEQUENA CIRURGIA', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('KIT TESTE DE URINA', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('KIT SONDAS DIVERSAS', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('KIT PARTO', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Lençóis com elástico', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('lençóis sem elástico', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Fronha', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Capa para cobertor', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Avental descartável manga longa', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Fluxômetro', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Frasco para aspiração ', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('silicone', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Máscara com reservatório adulto e pediátrica', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Nebulização adulto e pediátrico', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Cateter tipo óculos adulto e pediátrico', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Almotolia de Álcool', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Clorexidina Alcoólica', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Clorexidina Degermante', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Clorexidina Aquosa', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Água Oxigenada', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('SF 0,9% 100ml + Agulha 40x12', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Removedor de Esmalte - Acetona', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Caixa de Luva de Procedimento P - M - G', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Doutorzinho Creme', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Und Band Aid Adulto', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Und Band Aid Infantil', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Esparadrapo 10 cm', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Micropore 5 cm', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Abaixador de Língua', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Manta Térmica', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Pote com gaze não estéril', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Rolo Plástico', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Tesoura de resgate', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Respirador e Acessórios', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Traquéias', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Monitor + acessórios', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('kit pás ECG', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Finecare + Acessórios + teste', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Aspirador portátil', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Bombas de Infusão (BI) + cabo carregador', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('(06 seringas 50ML, 06 extensor,10 agulhas 40X12) ', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Balão teste ventilador  adu e inf', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Sensor de fluxo, conector adu, ped e neo', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Cabo para oxigênio', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('DEA ou cardiomax com função DEA', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Tesoura de resgaste', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Garrote', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Seringas 20 ml', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Seringas 10 ml', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Seringas 5 ml', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Seringas 3 ml', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Seringas 1 ml', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Scalp nº 21', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Scalp nº 23', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Scalp nº 25', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Scalp nº 27 ', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Abocath nº 16', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Abocath nº 18', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Abocath nº 20', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Abocath nº 22', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Abocath nº 24', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Agulhas 40x12', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Agulhas 30x08', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Agulhas 25x07', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Agulhas 13x4,5', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Agulhas Pediátricas 0,55x20', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Álcool Swab', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Luer Cap', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Cone Luer', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Abaixador de Língua', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Caixa de Band Aid', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Esparadrapo', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Micropore 5 cm', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Caixinha Stopper', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Equipos', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Polifix 2 vias', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Bloco de Receituário Simples ', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Bloco de Receituário Controlado', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Polifix 2 vias/ equipo simples', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Luva Plástica Descartável (EVA)', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Abaixadores de Língua', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Abocath nº 16', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Abocath nº 18', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Abocath nº 20', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Abocath nº 22', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Abocath nº 24', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Scalp nº 21', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Buscopan Simples gotas', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Buscopan Composto gotas', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Dramin B6 gotas', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Plasil / Metoclopramida gotas', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Dipirona gotas', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Paracetamol gotas', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('salbutamol spray', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Ipratrópio / Atrovent gotas', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Isossorbida 5mg e 20mg cp - cartela', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Atensina 0,100mg cp - cartela ', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Propanolol 40mg cp - cartela', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Paracetamol 750mg cp - cartela', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Dipirona 500mg cp - cartela', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Captopril 25mg cp - cartela', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('AAS 100mg cp - cartela', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Plasil / Metoclopramida 10mg cp - cartela', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Buscopan Simples 10mg cp - cartela', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Buscopan Composto cp -cartela', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Nifedipino - cartela', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('clopidogrel 75 mg cp/ cartela', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Cloreto de Sódio 0,9% 10ml', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Fenergan / Prometazina pomada', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Adenosina ', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Adrenalina ', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Água destilada 10ml', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Amiodarona', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Atropina', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Bicarbonato de Sódio 10ml', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Bromoprida', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Buscopan Composto', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Buscopan Simples', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Cloreto de Sódio 20% 10ml', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Cloreto de Potássio 10ml', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Dexametasona', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Deslanol AMP', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Diclofenaco', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Dipirona', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Dobutamina', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Dopamina', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Dramin B6 IM', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Frutovitan', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Fenergan / Prometazina', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Furosemida / Lasix', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Gluconato de Cálcio', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Glicose 50%', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Hidralazina', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Hidrocortisona (03) 100mg  + (02 ) 500mg', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Isossorbida', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Nipride / Nitroprussiato de sódio', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Noradrenalina', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Ondansetrona / Vonau', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Plasil / Metoclopramida', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Profenid / Cetoprofeno', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Terbutalina', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Fr. Suxametônio/Quelicin', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Fr. Fentanil/Fentanila  ', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('amp. Midazolam/Dormonid', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('amp. Hidantal/Fenitoína', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('amp. Diazepam/Valium ', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('cp. Diazepam/Valium ', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('amp. Tramadol/Tramal', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('amp. Clorpromazina/Amplictil ', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('amp. Flumazenil/Lanexat ', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('amp. Petidina/Dolantina', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('amp. Dimorf/Morfina', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('amp. Haloperidol/Haldol', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('amp. Narcan/Naloxona', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('amp Etomidato', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Fr.Quetamina', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Scalp nº 23', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Scalp nº 25', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Scalp nº 27', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Seringas 20 ml', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Seringas 10 ml', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Seringas 5 ml', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Seringas 3 ml', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Seringas 1 ml', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Agulhas 40x12', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Agulhas 30x08', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Agulhas 25x07', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Agulhas 13x4,5', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Agulhas Pediátricas 0,55x20', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Caixinha Stopper AD E INF', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Soro Fisiológico 0,9% 100ml', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('tesoura simples', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('micropore 10 cm', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('fita medicação pediátrica', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Tridil / Nitroglicerina', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Catéter Nasal tipo Óculos Adulto', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Catéter Nasal tipo Óculos Pediátrico', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Kit Nebulização Adulto', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Kit Nebulização Pediátrico', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Máscara de Venturi Adulto', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Máscara de Venturi Pediátrica', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Máscara com Reservatório Adulto', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Máscara com Reservatório Pediátrica', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Soro Fisiológico 0,9% 500ml', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Soro Fisiológico 0,9% 250ml', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Soro Fisiológico 0,9% 100ml', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Soro Glicosado 5% 250ml', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Pote com gaze não estéril', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Pote vazio para pérfuro-cortante', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('pares luva de procedimento P - M e G', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('EPI: Óculo de Proteção', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Compressa Gaze Estéril G', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Compressa Gaze Estéril P, ', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Ataduras Crepom 20cm', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Ataduras Crepom 15cm', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Ataduras Crepom 12cm', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Ataduras Crepom 10cm', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Rolo plástico', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Doutorzinho Creme', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Tesoura de resgate', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Kit Cânula de Guedel', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('TOT nº 2 - 3 - 4 -5', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('TOT nº 6 - 6,5 - 7 - 7,5 - 8', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Fio Guia Estéril', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Xilocaína gel', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Seringa 20ml', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Cadarço', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Máscara Laríngea nº 1 2 3  4 5', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Kit Laringo (Cabos + Lâminas + Pilhas)', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Maca Rígida', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Tirante Aranha adulto e pediátrico', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Jogo colar cervical PP - P - M - G', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Jogo base cabeça + coxins ', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Tala Papelão P - M - G', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Cilindros pequenos O2', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Cilindro Grande O2', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Papagaio (protegido com plástico)', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Comadre (protegido com plástico)', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Chave para cilindro O2', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Chave de roda', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Macaco', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Triângulo Sinalizador', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Vassoura de mão', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Sacos de Lixo Infectante', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Álcool 70% Frasco', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Compressas para Limpeza', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Soro Fisiológico 100 ml', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Soro Fisiológico 250 ml', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Soro Fisiológico 500 ml', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Soro Fisiológico 1000 ml', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Soro Glicosado 5% 250ml', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Ringer Lactato 500 ml', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Manitol 250 ml', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Máscara de Venturi Adulto', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Máscara de Venturi Pediátrica', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Máscara com reservatório Pediátrica', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('kit macro', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Máscara traqueo', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Máscara com reservatório adulto', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Espaçador', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Látex', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Catéter Nasal tipo óculos Adulto', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Catéter Nasal tipo óculos Pediátrico', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Filtro Bactericida para respirador ad e ped', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Fraldas descartáveis Adulto', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Fraldas descartáveis Pediátrica', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Frasco de Drenagem Torácica', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Coletor de Urina/Sistema Aberto', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Dreno de Tórax nº 22', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Dreno de Tórax nº 34', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Máscaras descartáveis', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Máscaras PFF2/N95', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Óculos de Proteção', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Celular - qual estado:', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Carregador celular', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Kit Respiratório', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Bolsa Kit Sutura', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Bolsa de Sondagem Vesical', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Bolsa de Sondas Diversas', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Bolsa de Ataduras', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Fraldas Adulto e Infantil', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Kit Parto', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Kit Drenagem de Tórax', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Kit roupas de cama maca', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Kit procedimento invasivos', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Kit Pequena cirurgia', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Avental de manga longa ', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Fluxômetro + umidificador (proteger)', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Frasco para aspiração (proteger)', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Pote Principal (aberto) Diversos', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Pote de  EPI´s', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Pote Grande: Materiais Esterilizados', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Pote Grande: Soro Fisiológico', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Passante', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Cadeira de rodas', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Descarpack + Suporte', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Maca rígida', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Tirante Aranha', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Jogo colar cervical G, M, P, PP', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Jogo base cabeça + coxins + tirantes', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Papagaio', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Comadre', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Suporte soro', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Colchão + Travesseiro + Cobertor', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Bloco ficha atendimento + prancheta', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Pastinha Azul', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Valor Cilindro de O2 grande', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Valor Cilindro de O2 pequeno', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Tem Cilindro de O2 reserva/lacrado', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Oxímetro com cabo adulto e neo', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Esfignomanômetro normal', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Esfignomanômetro obeso', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Esfignomanômetro infantil', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Estetoscópio', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Aparelho HGT + fitas', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Termômetro', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Desfibrilador Externo Automático-DEA', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Cardioversor+Eletrodos+Gel+Bobina ECG', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('sonar', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('otoscópio', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('ventilador e acessórios', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Bomba de infusão e acessórios', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('aspirador portátil', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('SF 500 ml', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('SF 250 ml', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('SF 100 ml', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('SG 250 ml', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Pote com gaze não estéril', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Pote vazio para pérfuro', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('pares luvas P M G', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Óculos Proteção EPI', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Atadura 20 cm', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Atadura 15 cm', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Atadura 12 cm', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Atadura 10 cm', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Rolo Plástico', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Compressas gaze estéril G', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Mantas térmicas', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Compressas gaze estéril P', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Tesoura Resgate', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Bloco Receituário Simples e controlado', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Medicações CP + GOTAS', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('fita med. Ped', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Garrote + tesoura + steri strip etc.', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Adenosina AMP', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Adrenalina AMP', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Água deslilada AMP', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Amiodarona AMP', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Atropina AMP', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Bicarbonato de sódio', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Bromoprida AMP', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Buscopan composto AMP', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Buscopan simples AMP', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Cloreto de sódio 20%  AMP', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Cloreto de potássio AMP', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Deslanol AMP', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Dexametasona AMP', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Diclofenaco AMP', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Dipirona AMP', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Dobutamina', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Dopamina AMP', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Dramin AMP', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Fenergan AMP', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Furosemida AMP', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Gluconato de cálcio AMP', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Amplictil AMP', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Diazepam AMP', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Diazepam CP', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Dimorf AMP', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Dolantina AMP', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Fentanil AMP', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Flumazenil AMP', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Haldol AMP', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Hidantal AMP', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Midazolan AMP', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Narcan AMP', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Suxametônio FR', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Tramal AMP', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Etomidato AMP', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Quetamina', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Glicose 50% AMP', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Hidrocortisona FR', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Hidralazina AMP', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Isossorbida AMP', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Nipride AMP', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Noradrenalina', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Ondasetrona AMP', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Plasil AMP', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Polivitamínico', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Profenid FR', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Terbutalina AMP', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Tridil AMP', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Gluconato de cálcio AMP', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Furosemida AMP', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Máscara Laríngea nº 1, 2,3, 4, 5', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Xylocaina', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Seringa 20 ml', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Cadarço', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Fio Guia', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('TOT nº 2 - 3 - 4 - 5-6,5-7-7,5-8', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Catéter nasal tipo óculos Adulto', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Catéter nasal tipo óculos Pediátrico', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Kit Nebu Adulto', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Kit Nebu Pediátrico', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Máscara venturi Adulto', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Máscara venturi Pediátrica', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Máscara alta concentração Adulto', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Mascara alta concetração pediatrica', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('kit cânula de guedel ', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Latex ', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Cabo Laringo Adulto e Pediátrico', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Qtdade lâminhas curvas (testar)', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Qtdade lâminhas retas (testar)', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Jogo de Pilhas', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Garrote', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Seringa 20 ml', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Seringa 10 ml', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Seringa 5 ml', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Seringa 3 ml', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Seringa 1 ml', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Scalp nº 21', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Scalp nº 23', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Scalp nº 25', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Scalp nº 27 ', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Abocath nº 16', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Abocath nº 18', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Abocath nº 20', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Abocath nº 22', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Abocath nº 24', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Agulha 40X12', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Agulha 30X8', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Agulha 25X7', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Agulha 13X4,5', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Álcool Swab', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Luer Cap', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Polifix', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('equipos', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Cone Luer', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Abaixador de Língua Adulto e Infantil', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Caixa de Band Aid', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Esparadrapo 10 cm', NOW(), NOW(), 2);
INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Micropore 5 cm', NOW(), NOW(), 2);


INSERT INTO public."Items" ("Name", "CreatedAt", "UpdatedAt", "TenantId") VALUES ('Mascara', NOW(), NOW(), 2);